name: CI/CD Pipeline

on: [push, pull_request, workflow_dispatch]

jobs:
  cd:
    name: Continuous Deployment
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        id: checkout_repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Determine project version
        id: determine_project_version
        shell: pwsh
        run: |
          $latestGitVersion = (git tag --list 'SmartEnum-*' --sort=-committerdate)[0] -replace 'SmartEnum-v', ''
          $filePath = (Get-ChildItem .\src\SmartEnum\SmartEnum.csproj).FullName
          $projectVersion = [String](([xml](Get-Content $filePath)).Project.PropertyGroup.Version)
          $newVersion = ' '
          $isNewTag = 'false'
          $versionsList = ($projectVersion, $latestGitVersion)
          $versionsList | Foreach-Object {echo $_}
