name: CI/CD Pipeline

on: [push, pull_request, workflow_dispatch]

jobs:
  cd:
  - name: Continuous Deployment
    needs: ci
    runs-on: windows-latest
    steps:
      - name: Setup dotnet
        id: setup_dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.300

      - name: Checkout repository
        id: checkout_repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Download and extract Artifacts
        id: dl_artifact
        uses: actions/download-artifact@v2
        with:
          name: NuGet Packages
          path: NuGet/

      - name: Determine project version
        id: determine_project_version
        shell: pwsh
        run: |
          $latestGitVersion = (git tag --list 'SmartEnum-*' --sort=-committerdate)[0] -replace 'SmartEnum-v', ''
          $filePath = (Get-ChildItem .\src\SmartEnum\SmartEnum.csproj).FullName
          $projectVersion = ([xml](Get-Content $filePath)).Project.PropertyGroup.Version
          $newVersion = ''
          $isNewTag = 'false'
          $versionsList = $projectVersion, $latestGitVersion

          if ( $projectVersion -ne $latestGitVersion -and $projectVersion -eq ($versionsList | Sort { [System.Version] $_ } -Descending)[0] ) {
            $newVersion = $projectVersion
            $isNewTag = 'true'
            $smartEnumTag = "SmartEnum-v$newVersion"
            git push origin "$isNewTag"
          }

          Write-Output "::set-output name=new_version::$(echo $newVersion)"
          Write-Output "::set-output name=is_new_tag::$(echo $isNewTag)"

      - if: steps.determine_project_version.outputs.is_new_tag == 'true'
        name: Create and publish release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: SmartEnum ${{ steps.determine_project_version.outputs.new_version }}
          tag_name: SmartEnum-v${{ steps.determine_project_version.outputs.is_new_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
