name: CI/CD Pipeline

on: [push, pull_request, workflow_dispatch]

jobs:
  cd:
    name: Continuous Deployment
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        id: checkout_repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Determine project version
        id: determine_project_version
        shell: pwsh
        run: |
          $latestGitVersion = (git tag --list 'SmartEnum-*' --sort=-committerdate)[0] -replace 'SmartEnum-v', ''
          $filePath = (Get-ChildItem .\src\SmartEnum\SmartEnum.csproj).FullName
          $projectVersion = [String](([xml](Get-Content $filePath)).Project.PropertyGroup.Version)
          $newVersion = ''
          $isNewTag = 'false'
          $versionsList = ($projectVersion, $latestGitVersion)

          if ( $projectVersion -ne $latestGitVersion -and $projectVersion -eq ($versionsList | Sort { [Version] $_ } -Descending)[0] ) {
            $newVersion = $projectVersion
            $isNewTag = 'true'
            $smartEnumTag = "v$newVersion"
            git tag -a $smartEnumTag
            git push –tags $smartEnumTag
          }

          Write-Output "::set-output name=new_version::$(echo $newVersion)"
          Write-Output "::set-output name=is_new_tag::$(echo $isNewTag)"

