name: CI/CD Pipeline

on: [push, pull_request, workflow_dispatch]

jobs:
  ci:
    name: Continuous Integration
    runs-on: windows-latest
    outputs:
      new_version: ${{ steps.determine_project_version.outputs.new_version }}
    steps:
      - name: Checkout repository
        id: checkout_repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Determine project version
        id: determine_project_version
        shell: pwsh
        run: |
          $latestGitVersion = (git tag --list 'SmartEnum-*' --sort=-committerdate)[0] -replace 'SmartEnum-v', ''
          $filePath = (Get-ChildItem .\src\SmartEnum\SmartEnum.csproj).FullName
          $projectVersion = [String](([xml](Get-Content $filePath)).Project.PropertyGroup.Version)
          $newVersion = ''
          $isNewTag = 'false'
          $versionsList = ($projectVersion, $latestGitVersion)

          if ( $projectVersion -ne $latestGitVersion -and $projectVersion -eq ($versionsList | Sort { [Version] $_ } -Descending)[0] ) {
            $newVersion = "$projectVersion" -replace '\s', ''
            $isNewTag = 'true'
            $smartEnumTag = "SmartEnum-v$newVersion" -replace '\s', ''
          }

          Write-Output "::set-output name=smartenum_tag::$(echo $smartEnumTag)"
          Write-Output "::set-output name=new_version::$(echo $newVersion)"
          Write-Output "::set-output name=is_new_tag::$(echo $isNewTag)"
          
      - name: Create and publish release
        id: create_release
        shell: pwsh
        run: |
          $releaseTag = "${{ steps.determine_project_version.outputs.smartenumm_tag }}"
          $releaseTitle = "SmartEnum ${{ steps.determine_project_version.outputs.new_version }}"

          gh release create $releaseTag --title $releaseTitle
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
